name: SkyWars
main: dev._2lstudios.skywars.SkyWars
version: 0.0.1
author: 2LS
softdepend:
  - PlaceholderAPI
  - Vault
  - Scoreboard
commands:
  skywars:
    description: Main SkyWars command
    usage: /skywars
    aliases: [sw]
  leave:
    description: Leave the SkyWars arena
    usage: /leave
    aliases: [salir, s]
  party:
    description: SkyWars party commands
    usage: /party
    aliases: [p]
load: POSTWORLD